Updated npaste cli-script with error message when server does not support download or paste does not exist

diff --git a/cli-script/npaste b/cli-script/npaste
--- a/cli-script/npaste
+++ b/cli-script/npaste
@@ -209,6 +209,10 @@ if [ "$NPASTE_PASTE_ID" != "" ]; then
             fi
         fi
     fi
+    if [ "$STATUSCODE" == "404" ]; then
+        echo "Paste not found or server does not support downloads."
+        exit 1
+    fi
     exit 0
 fi
 
